a = " Hello Gautam Buddha University" 
print("String operations\n")
print("Original String : ", a) 
print("Coverts all to lowercase : ",a.lower())
print("converts all to uppercase : ",a.upper()) 
print("Swaps the cases of alphabets : ", a.swapcase())
print("Checks whether the string is alphabet or not : ",a.isalpha()) 
print("Checks whether the string is digit or not : ", a.isdigit()) 
print("First index of the letter in the given string : ", a.index("r")) 
print("Counts the letter it occoured: ", a.count("a")) 
print("Splits the string using delimeter : ", a.split(" ")) 
print("Replaces the world with the given string : ", a.replace("Hello", "Hi")) 
print("Checks whether the string end with given word : ", a.endswith("d")) 
